language: php

php:
  - "7.1"

before_install:
  - composer self-update
  - cp .env.travis .env

install:
  - composer install --no-interaction --no-suggest --no-progress --optimize-autoloader

script:
  - php vendor/bin/phpunit
